### ISSUE TITLE
Problem with superimposing fragments

### ISSUE THREAD

**Issue by dhingra-s** [Hoecker-Lab/protlego#1]
Hello,

I am trying to build chimeras following the same commands as shown in the protlego paper.
The server is giving error at the step of building all possible chimeras. 
Please find the commands run and the errors below :

>>> chimeras={}
>>> for index,hit in enumerate(hits.hits):
...     a=Builder(hit)
...     aln=a.get_alignment(hit.query,hit.no)
...     a.superimpose_structures(aln,partial_alignment=True)
...     chimeras[index]=a.build_chimeras(partial_alignment=True)
... 
2021-01-21 10:17:12,862 - protlego - INFO - Attempting to download domain d3w5ja1 from the SCOP server
2021-01-21 10:17:14,182 - protlego - INFO - File downloaded as /tmp/user/1307247/tmpvbeiaq11.pdb
2021-01-21 10:17:14,183 - protlego - INFO - Attempting to download domain d1hyha1 from the SCOP server
2021-01-21 10:17:15,167 - protlego - INFO - File downloaded as /tmp/user/1307247/tmp6yqbl8rg.pdb
2021-01-21 10:17:15,167 - protlego - INFO - Loading /tmp/user/1307247/tmpvbeiaq11.pdb as a chimera object
2021-01-21 10:17:15,544 - protlego - INFO - Loading /tmp/user/1307247/tmp6yqbl8rg.pdb as a chimera object
2021-01-21 10:17:15,579 - protlego - INFO - Attempting to download hhs file for d3w5ja1 from the FUZZLE server
2021-01-21 10:17:15,677 - protlego - INFO - File downloaded as /tmp/user/1307247/tmp_h8zflg8.hhs
2021-01-21 10:17:16,358 - protlego - INFO - Performing alignment 1 with TMalign
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/agh/projects/sdhingra/miniconda3/envs/protenv/lib/python3.6/site-packages/protlego/builder/builder.py", line 246, in superimpose_structures
    saPDB, distance = self._superimpose_chunk(qpair_chunk, spairs[index], qmol, smol)
  File "/agh/projects/sdhingra/miniconda3/envs/protenv/lib/python3.6/site-packages/protlego/builder/builder.py", line 297, in _superimpose_chunk
    data = rmsd.project(copys)
  File "/agh/projects/sdhingra/miniconda3/envs/protenv/lib/python3.6/site-packages/moleculekit/projections/metricrmsd.py", line 98, in project
    mol.wrap(getMolProp('centersel'))
  File "/agh/projects/sdhingra/miniconda3/envs/protenv/lib/python3.6/site-packages/moleculekit/molecule.py", line 1475, in wrap
    "Zero box size detected in `Molecule.box`. Cannot wrap simulation."
RuntimeError: Zero box size detected in `Molecule.box`. Cannot wrap simulation.

Could you please help solve this issue.

Thanks
Surbhi

**Comment by noeliaferruz** [comment]
Hi Surbhi,

Thanks for reporting. I am running this exact code in the same environment and it runs smoothly. Here is my jupyter-notebook:  /agh/projects/noelia/bkp.protlego/docs/protlego_paper.ipynb in case it helps.

A few things that came to my mind. Have you checked the files exist in /tmp/user/1307247/...?
Also, do you know why they get downloaded there? I believe they should go to /tmp/ directly. Does the folder /tmp/user... exist?
If the files exist, could you please send them to me?

Another thought, just to check we really are running the same versions of everything, could you type me the output of conda list? 

Thanks a lot!
Noelia

**Comment by dhingra-s** [comment]
Hey,

Thanks for responding.

So, I looked into /tmp/user/. Do not have permission to view what is inside.
Quick question. Where should /tmp/user/ exist??

Here is conda list you asked for : 

# packages in environment at /agh/projects/sdhingra/miniconda3/envs/protenv:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
argon2-cffi               20.1.0           py36h7b6447c_1  
astunparse                1.6.3                      py_0  
async_generator           1.10             py36h28b3542_0  
at-spi2-atk               2.38.0               hdfca744_2    conda-forge
at-spi2-core              2.38.0               hdfca744_2    conda-forge
atk-1.0                   2.36.0               h28cd5cc_0  
attrs                     20.3.0             pyhd3eb1b0_0  
backcall                  0.2.0                      py_0  
blas                      1.0                         mkl  
bleach                    3.2.1                      py_0  
blosc                     1.20.1               hd408876_0  
boost                     1.74.0           py36h8e82bdb_2    conda-forge
boost-cpp                 1.74.0               h9d3c048_1    conda-forge
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2021.1.19            h06a4308_0  
cairo                     1.16.0            h7979940_1007    conda-forge
cairomm                   1.12.2               ha770c72_3    conda-forge
cairomm-1.0               1.12.2               h56b4340_3    conda-forge
certifi                   2020.12.5        py36h06a4308_0  
cffi                      1.14.4           py36h261ae71_0  
csb                       1.2.5              pyh24bf2e0_2    bioconda
cudatoolkit               10.2.89              hfd86e86_1  
cycler                    0.10.0                   py36_0  
dbus                      1.13.18              hb2f20db_0  
decorator                 4.4.2                      py_0  
defusedxml                0.6.0                      py_0  
entrypoints               0.3                      py36_0  
epoxy                     1.5.5                h7f98852_0    conda-forge
expat                     2.2.10               he6710b0_2  
fftw                      3.3.9                h27cfd23_1  
fontconfig                2.13.1            hba837de_1004    conda-forge
freetype                  2.10.4               h5ab3b9f_0  
fribidi                   1.0.10               h7b6447c_0  
future                    0.18.2                   py36_1  
gdk-pixbuf                2.42.2               h0c95a7a_2    conda-forge
gettext                   0.19.8.1             h9b4dc7a_1  
glib                      2.66.4               hcd2ae1e_1    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
gobject-introspection     1.66.1           py36h94476cb_0  
graph-tool                2.37             py36hf3098de_1    conda-forge
graphite2                 1.3.14               h23475e2_0  
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.18.3               h3560a44_0    conda-forge
gtk3                      3.24.24              ha6843f1_1    conda-forge
harfbuzz                  2.7.4                h5cf4720_0    conda-forge
hdf5                      1.10.4               hb1b8bf9_0  
hicolor-icon-theme        0.17                 ha770c72_2    conda-forge
htmd-pdb2pqr              0.0.2                      py_0    conda-forge
icu                       68.1                 h58526e2_0    conda-forge
importlib-metadata        2.0.0                      py_1  
importlib_metadata        2.0.0                         1  
intel-openmp              2020.2                      254  
ipykernel                 5.3.4            py36h5ca1d4c_0  
ipython                   7.12.0           py36h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                7.6.3              pyhd3eb1b0_1  
jedi                      0.18.0           py36h5fab9bb_2    conda-forge
jinja2                    2.11.2             pyhd3eb1b0_0  
jpeg                      9d                   h36c2ea0_0    conda-forge
jsonschema                3.2.0                      py_2  
jupyter                   1.0.0                    py36_7  
jupyter_client            6.1.7                      py_0  
jupyter_console           6.2.0                      py_0  
jupyter_core              4.7.0            py36h06a4308_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1  
kiwisolver                1.3.0            py36h2531618_0  
krb5                      1.17.1               h173b8e3_0  
lcms2                     2.11                 h396b838_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libclang                  11.0.1          default_ha53f305_1    conda-forge
libcups                   2.2.12               hf10b501_1    conda-forge
libedit                   3.1.20191231         h14c3975_1  
libevent                  2.1.10               hcdb4288_3    conda-forge
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h2828fa1_18    conda-forge
libgfortran-ng            7.3.0                hdf63c60_0  
libglib                   2.66.4               h164308a_1    conda-forge
libgomp                   9.3.0               h2828fa1_18    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libllvm10                 10.0.1               hbcb73fb_5  
libllvm11                 11.0.1               hf817b99_0    conda-forge
libpng                    1.6.37               hbc83047_0  
libpq                     12.3                 h255efa7_3    conda-forge
librsvg                   2.50.2               h115801e_2    conda-forge
libsodium                 1.0.18               h7b6447c_0  
libstdcxx-ng              9.3.0               h6de172a_18    conda-forge
libtiff                   4.1.0                h2733197_1  
libuuid                   2.32.1            h7f98852_1000    conda-forge
libxcb                    1.14                 h7b6447c_0  
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.10               h72842e0_3    conda-forge
llvmlite                  0.34.0           py36h269e1b5_4  
lz4-c                     1.9.2                heb0550a_3  
lzo                       2.10                 h7b6447c_2  
markupsafe                1.1.1            py36h7b6447c_0  
matplotlib                3.3.2                h06a4308_0  
matplotlib-base           3.3.2            py36h817c723_0  
mdtraj                    1.9.5            py36hab346d7_0    conda-forge
mistune                   0.8.4            py36h7b6447c_0  
mkl                       2020.2                      256  
mkl-service               2.3.0            py36he8ac12f_0  
mkl_fft                   1.2.0            py36h23d657b_0  
mkl_random                1.1.1            py36h0573a6f_0  
mock                      4.0.3              pyhd3eb1b0_0  
moleculekit               0.6.0                    py36_0    acellera
mysql-common              8.0.22               ha770c72_1    conda-forge
mysql-libs                8.0.22               h1fd7589_1    conda-forge
nbclient                  0.5.1                      py_0  
nbconvert                 6.0.7                    py36_0  
nbformat                  5.1.2              pyhd3eb1b0_1  
ncurses                   6.2                  he6710b0_1  
nest-asyncio              1.4.3              pyhd3eb1b0_0  
networkx                  2.5                        py_0  
ninja                     1.10.2           py36hff7bd54_0  
notebook                  6.1.6            py36h06a4308_0  
nspr                      4.29                 h9c3ff4c_1    conda-forge
nss                       3.60                 hb5efdd6_0    conda-forge
numba                     0.51.2           py36h0573a6f_1  
numexpr                   2.7.2            py36hb2eb853_0  
numpy                     1.19.2           py36h54aff64_0  
numpy-base                1.19.2           py36hfa32c7d_0  
ocl-icd                   2.2.14               h7f98852_0    conda-forge
ocl-icd-system            1.0.0                         1    conda-forge
olefile                   0.46                     py36_0  
openmm                    7.5.0            py36ha444293_4    conda-forge
openssl                   1.1.1i               h27cfd23_0  
packaging                 20.8               pyhd3eb1b0_0  
pandas                    1.1.3            py36he6710b0_0  
pandoc                    2.11                 hb0f4dca_0  
pandocfilters             1.4.3            py36h06a4308_1  
pango                     1.42.4               h69149e4_5    conda-forge
parmed                    3.2.0            py36hc4f0c31_4    conda-forge
parso                     0.8.1              pyhd3eb1b0_0  
pcre                      8.44                 he6710b0_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    8.1.0            py36he98fc37_0  
pip                       20.3.3           py36h06a4308_0  
pixman                    0.40.0               h7b6447c_0  
prometheus_client         0.9.0              pyhd3eb1b0_0  
prompt-toolkit            3.0.8                      py_0  
prompt_toolkit            3.0.8                         0  
propka                    3.4.0            py36he448a4c_1    conda-forge
protlego                  1.0.10           py36h39e3cac_0    nferruz
ptyprocess                0.7.0              pyhd3eb1b0_2  
pycairo                   1.19.1           py36h2a1e443_0  
pycparser                 2.20                       py_2  
pygments                  2.7.4              pyhd3eb1b0_0  
pygobject                 3.38.0           py36he855594_4    conda-forge
pyparsing                 2.4.7              pyhd3eb1b0_0  
pyqt                      5.12.3           py36h5fab9bb_7    conda-forge
pyqt-impl                 5.12.3           py36h7ec31b9_7    conda-forge
pyqt5-sip                 4.19.18          py36hc4f0c31_7    conda-forge
pyqtchart                 5.12             py36h7ec31b9_7    conda-forge
pyqtwebengine             5.12.1           py36h7ec31b9_7    conda-forge
pyrsistent                0.17.3           py36h7b6447c_0  
pytables                  3.6.1            py36h71ec239_0  
python                    3.6.12               hcff3b4d_2  
python-dateutil           2.8.1                      py_0  
python_abi                3.6                     1_cp36m    conda-forge
pytz                      2020.5             pyhd3eb1b0_0  
pyzmq                     20.0.0           py36h2531618_1  
qt                        5.12.9               h9d6b050_2    conda-forge
qtconsole                 4.7.7                      py_0  
qtpy                      1.9.0                      py_0  
readline                  8.0                  h7b6447c_0  
scipy                     1.5.2            py36h0b6359f_0  
send2trash                1.5.0              pyhd3eb1b0_1  
setuptools                51.3.3           py36h06a4308_4  
sigcpp-2.0                2.10.3               h58526e2_0    conda-forge
six                       1.15.0           py36h06a4308_0  
snappy                    1.1.8                he6710b0_0  
sparsehash                2.0.2                         0    bioconda
sqlite                    3.34.0               h74cdb3f_0    conda-forge
tbb                       2020.3               hfd86e86_0  
terminado                 0.9.2            py36h06a4308_0  
testpath                  0.4.4                      py_0  
tk                        8.6.10               hbc83047_0  
tornado                   6.1              py36h27cfd23_0  
tqdm                      4.55.1             pyhd3eb1b0_0  
traitlets                 4.3.3                    py36_0  
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py36_1  
wheel                     0.36.2             pyhd3eb1b0_0  
widgetsnbextension        3.5.1                    py36_0  
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.12               h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h27cfd23_1007  
xz                        5.2.5                h7b6447c_0  
zeromq                    4.3.3                he6710b0_3  
zipp                      3.4.0              pyhd3eb1b0_0  
zlib                      1.2.11               h7b6447c_3  
zstandard                 0.14.1           py36h2531618_0  
zstd                      1.4.5                h9ceee32_0  

Hope this helps
Surbhi

**Comment by noeliaferruz** [comment]
No, I don't know why it tries to download in that folder, it should be /tmp/. I don't have a folder /tmp/user either.

You can try to force moleculekit to be on version 0.1.22. This way we are exactly on the same version. It's that package who's throwing the error.

**Comment by noeliaferruz** [comment]
This is mine: 
`moleculekit               0.1.22           py36h861eeaf_0    acellera`

**Comment by noeliaferruz** [comment]
Hi Surbhi, any updates?

**Comment by dhingra-s** [comment]
Hey,

Excuse me for not replying. Didn't want to distract you from your urgent commitments.

Anyway, updating moleculekit worked.
Now, Chimera building step is working but it is running much longer (couple of hours) than the time stated in your experiments.
Also, the run was not complete as /tmp/ space in my desktop was full. Have you encountered similar issues?

How do you suggest I should proceed here??

Another query. 
While going through protlego tutorial, most of the commands generated some output except for 'view' (Ex: qPDB[0].view()). Is it that user have to install VMD separately or was the package missed during protlego installation.

I did check your installation list. Didn't seem to find it. 

Thanks for your help....:)

Surbhi

**Comment by noeliaferruz** [comment]
Hi, very nice!

The construction of chimeras is usually very fast, a few seconds per hit. In the code above you are building hundreds of thousands of chimeras, that is, all chimeras between the c.2 and the c.37 folds. (which perhaps you don't need to do again). This code also took me a few hours, (12 000s =3.5 h). If it takes a few more in your case must be due to differences in our workstations.

I imagine /tmp/ getting full when building so many chimeras... When building chimeras in such a high throughput fashion, I'd thus purge /tmp from time to time with a cronjob.  But I guess you usually will want to build a few chimeras (max. hundreds?).

The command view() always calls vmd, yes. It's installed on our computers. Before loading your protlego conda environment, load the module VMD (not sure how it's called but it's in module avail). This way you will see the windows, whenever you are using jupyter notebook or another interactive platform.

Hope this helps!

**Comment by dhingra-s** [comment]
Hey,

Makes sense. I was wondering if creating that many chimeras was needed.

Thanks for all the clarifications....:)
