### ISSUE TITLE
No module named Graph_Tool

### ISSUE THREAD

**Issue by sahincan** [Hoecker-Lab/protlego#3]
Hello everyone!

I have successfully installed with conda. But when I try 

from protlego.all import *

code, I get ModuleNotFoundError: No module named 'graph_tool' error. 

I checked graph_tool version, It is installed. 

I tried to install this instructions, https://git.skewed.de/count0/graph-tool/-/wikis/installation-instructions   get error again. 
Even I tried the installing from environment file, I get same error again.

How can I solve this error?

**Comment by noeliaferruz** [comment]
Hi sahican!

Thanks a lot for installing protlego and reporting this.
What is the output of conda list?

sahincan ***@***.***> schrieb am Sa. 8. Mai 2021 um 13:32:

**Comment by sahincan** [comment]
Solved ! 
It gives dependencies conflict warning when install protego with pip. Protlego is also loaded when installing with conda, but grap_tool does not. When installing with from environment, grap tool is not installed. 

AS A SOLUTION, 
1) Install Protlego via conda
2) conda activate myenv, I
3) Install graph tool pip via terminal     `pip install graph-tools`
https://pypi.org/project/graph-tools/
4) open jupyter and write 
`import protlego
from protlego.all import *`
It works for me!
